apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-multitool
  labels:
    app: multitool
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: "{{ .Values.multitool.image }}:{{ .Values.multitool.tag }}"
        env:
        - name: HTTP_PORT
          value: "{{ .Values.multitool.port }}"

