apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-dep
  namespace: dgv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-conditional
  template:
    metadata:
      labels:
        app: nginx-conditional
    spec:
      initContainers:
      - name: wait-15-seconds
        image: busybox:1.36
        command: ['sh', '-c', 'echo "Начинаем симуляцию ожидания..."; sleep 15; echo "Время вышло, запускаем основной контейнер!"']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
