apiVersion: v1
kind: PersistentVolume
metadata:
  name: sc-local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-class
  hostPath:
    path: /data/k8s-sc-volume
