apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-data-app
  template:
    metadata:
      labels:
        app: sc-data-app
    spec:
      containers:
      - name: writer-busybox
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: ["while true; do echo $(date) >> /mnt/sc/data.log; sleep 5; done"]
        volumeMounts:
        - name: sc-storage
          mountPath: /mnt/sc
      - name: reader-multitool
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["tail -f /mnt/sc/data.log"]
        volumeMounts:
        - name: sc-storage
          mountPath: /mnt/sc
      volumes:
      - name: sc-storage
        persistentVolumeClaim:
          claimName: sc-pvc
